### PR TITLE
Blog Post - Lambda calculus

### PR DESCRIPTION
**Pull request by srodrigo**

### CODE REVIEW

**Comment by cyplo** [comment]
Heyo, this looks good to me, do we need anything else to get this merged ?

**Comment by srodrigo** [comment]
Not yet @cyplo I need to change the post date.
I've got a question about this... I don't really know if it's ok to merge and it will show up on the specified date, or if the website needs to be redeployed.

**Comment by MiyamotoAkira** [comment]
The site needs to be redeployed after the date is past

**Comment by srodrigo** [comment]
I've updated the date to Thursday, when it's to be published.

**Review by rachelcarmena — APPROVED** [review]

**Review by PaNaVTEC — APPROVED** [review]

**Pull request merged**
