### PR TITLE
Thumbnail image updates

### PR DESCRIPTION
**Pull request by anguspaterson**
Update thumbnails to ensure design consistency

### CODE REVIEW

**Comment by keith-smale** [comment]
Changes included from other branches/PR's.

**Comment by keith-smale** [comment]
Only one of the three images you added is actually being used.

**Comment by anguspaterson** [comment]
Thanks @keith-smale, appricate comment regarding PR.

**Comment by anguspaterson** [comment]
A clean version of PR here: https://github.com/codurance/site/pull/1481

**Pull request closed without merging**
