### PR TITLE
putting team's pictures in multiple rows - fixes #500

### LINKED ISSUE #500: Team photos should overflow from the left
The last row in the matrix of photos on the "Company" page puts the new photo on the right, which is a bit unexpected. Please see the bottom of the screenshot. /cc @mashooq  screen shot 2017-01-05 at 17 31 31

### PR DESCRIPTION
**Pull request by ghost**
image

### CODE REVIEW

**Comment by cyplo** [comment]
@mashooq @PaNaVTEC it seems that we're getting Circle CI status here as well - not sure if intended.

**Comment by cyplo** [comment]
@halimakoundi how does it look on smaller screens ?

**Comment by PaNaVTEC** [comment]
Hey @cyplo so @mashooq and myself just press the build button in Circle CI and now it seems that is trying to build for every PR. I am going to try to disable it for now. I will play with site-preview and after everything is ok I will migrate the configuration here.

**Comment by ghost** [comment]
image

**Pull request merged**
