### PR TITLE
Fix image width because of class row blog page img

### PR DESCRIPTION
**Pull request by ananogal**
Added a script to Publication page

### CODE REVIEW

**Comment by neomatrix369** [comment]
These URLs would need some checking just to ensure the fix in this PR does not cause new regression. Although this is not a silver-bullet, but these came up with the site comparison tool, do also check in other places:

http://localhost:4000/2014-07-27-tell-dont-ask
http://localhost:4000/publications/tag/clean-architecture
http://localhost:4000/publications/tag/lego
http://localhost:4000/publications/tag/prompt
http://localhost:4000/publications/tag/rest
http://localhost:4000/publications/tag/sprint
http://localhost:4000/publications/tag/swagger
http://localhost:4000/publications/tag/tutorial
http://localhost:4000/publications/tag/vscode
http://localhost:4000/2016/10/16/setting-up-scala-on-android
http://localhost:4000/2014/04/10/keeping-the-domain-in-core
http://localhost:4000/2014/07/18/queue-based-synchronisation
http://localhost:4000/es/2015/06/13/big-data-skills-spectrum
http://localhost:4000/software-creation/2016/08/08/communicating-design
http://localhost:4000/2015/06/13/big-data-skills-spectrum
http://localhost:4000/2015/09/14/clojure-schemas-are-swagger
http://localhost:4000/2016/02/08/command-prompt-envy
http://localhost:4000/2016/10/06/database-testing-with-tsqlt
http://localhost:4000/development/2013/01/12/spring-integration-based-dispatcher-worker-with-worker-queues/
http://localhost:4000/es/2014/07/18/queue-based-synchronisation
http://localhost:4000/es/2014/04/10/keeping-the-domain-in-core
http://localhost:4000/2016/10/03/when-a-good-architecture-helps-you-in-your-ui-design-iterations
http://localhost:4000/events

I hope this helps.

**Comment by ananogal** [comment]
I've seen all the URLs, and with this Fix, they all look nice, in desktop mode as well as on mobile. I think it's ready to be merged.

**Comment by cyplo** [comment]
The linked-in preview seems a bit off, @PaNaVTEC - would it be okay for you to take a look ?

**Comment by PaNaVTEC** [comment]
@cyplo Sure I'm taking a look

**Comment by neomatrix369** [comment]
Re-ran the scan of all the pages, they look good. 👍 @ananogal

**Pull request merged**
