### PR TITLE
Seans bio

### PR DESCRIPTION
**Pull request by sjn88**

### CODE REVIEW

**Review by jukecraft — COMMENTED** [review]
Personally, I'd remove the specialisation

**Comment by dhatanian** [comment]
Fine to me, happy to merge unless other people have comments (poke @franziskas )

**Comment by sjn88** [comment]
@franziskas What specialisation?

**Comment by jukecraft** [comment]
`His current interest is machine learning, due to an unhealthy obsession with matrices that started in his degree in Natural Sciences, specialising in Material Science and Metallurgy.`
I think this is too specific - I think your recent project experience would be more relevant than what you specialised in in uni. The `unhealthy` part sounds a bit unprofessional, but it's your choice. Merge it if you don't agree :)

**Comment by sjn88** [comment]
Good point, I do like to brag I did a cool degree. I think the unhealthy obsession thing is funny and ties into the informal branding well. I will consider this feedback now.

**Pull request merged**
