### PR TITLE
Add Przemek Rogowski profile and change position to craftsperson

### PR DESCRIPTION
**Pull request by przemek-rogowski**
This PR:

Adds Przemek Rogowski's bio note to the "Our People" page.
Adds Przemek Rogowski's profile picture to "Our People" assets.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Why change all the craftsman to craftsperson?

**Comment by jfacchini** [comment]
Agreed with @pepperrone, I thought it was the choice of each individual to choose their pronoun

**Comment by przemek-rogowski** [comment]
Emily Reboul asked me to do that. In general, two versions were mixed there. Craftsman and Craftsperson. One could think what is the difference.

**Comment by ghost** [comment]
This probably should be discussed in the channel first. You can add your card to the PR and we can make another PR for the pronouns later if that's the case or open an issue.

**Comment by przemek-rogowski** [comment]
I reverted the changes related to craftswoman/craftsman -> craftsperson. Please review.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
