### PR TITLE
Fix broken links on blog post pages

### LINKED ISSUE #510: Fix broken links in blog pages
Linked to parent issue #503.

Links to external (mostly) websites on blogs written under the https://codurance.com/publications/ page were incorrect originally or the links changed over time.

### PR DESCRIPTION
**Pull request by neomatrix369**
Links to external (mostly) websites on blogs written under the https://codurance.com/publications/ page were incorrect originally or the links changed over time, this PR fixes them.

Not all issues are fixed with this PR, a number of them are pending - either unresolvable or needs further discussion, can be found in this document [Deadlinks on Codurance.com](https://docs.google.com/document/d/1SDNZlK2Yqrl2t0KZHTWCrx3aL47G2XsJ7pOtyIuquzY/edit#).

Fixes #510.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Rebasing the branch, will push again when fixed.

**Comment by neomatrix369** [comment]
@pedromsantos @ananogal please let me know if you are happy with these two commits:
- Replaced C# with CSharp, as tag generators do not like the hash (#) 		127e7fa
- Replaced F# with FSharp, as tag generators do not like the hash (#) 		22b14e1

**Comment by neomatrix369** [comment]
Both @pedromsantos & @ananogal confirmed they are happy with the change in the tags - thanks again.

**Comment by cyplo** [comment]
I've checked random links that are http-only and all of them can be made https. Would it be alright to make all of the links use https ?

**Comment by cyplo** [comment]
What would be a good mechanism to prevent broken links reappearing in the future ? A linter in the build process ? A scraper run periodically ?

**Comment by neomatrix369** [comment]
@cyplo About broken link in the future, a linter in the build process can be an idea or a nightly build that checks for broken links, as this process is time consuming, can slow down our build pipeline even though we might not use this intensively. 

I have used this site http://www.deadlinkchecker.com/ to check for dead links.

**Comment by neomatrix369** [comment]
@cyplo About the comments on `https` and `http` - I'm happy to change all of them to `http`, I don't see why we should have `https` for any of them, unless necessary.

**Comment by neomatrix369** [comment]
@cyplo As agreed, all links are now using `https` protocol, except for one which does not support it.

**Comment by neomatrix369** [comment]
@cyplo About broken links analysis, we decided that we will try to use the enhancement issue #418, continued at #512

**Comment by cyplo** [comment]
Please see #513 for the continuation of this work.

**Review by cyplo — APPROVED** [review]

**Pull request merged**
