### PR TITLE
Fix: removing images with text and unnecessary alternative texts

### PR DESCRIPTION
**Pull request by rachelcarmena**
Hi colleagues, I made several mistakes when writing my posts. I hope this is the last one in order not to disturb you. 
In this case, I'm removing images with text and unnecessary alternative texts (an empty alt attribute is valid when it's not necessary to provide the information of the existence of that image). 
Thanks in advance!

### CODE REVIEW

**Review by MiyamotoAkira — APPROVED** [review]

**Review by MiyamotoAkira — CHANGES_REQUESTED** [review]
Just having a second look. Maybe is better to have the actual lines inlined within the posts, using triple quote, rather than pointing to the gist.

**Comment by rachelcarmena** [comment]
Good idea, @MiyamotoAkira ! I gonna change it!

**Comment by rachelcarmena** [comment]
Done @MiyamotoAkira ! Merging with remote repository (the additional one), rebasing, amending and pushing with force. So, PR with only one commit again. I know you like a clean commit history :wink:

**Review by MiyamotoAkira — APPROVED** [review]

**Comment by rachelcarmena** [comment]
Thanks @MiyamotoAkira !! :dancer:

**Pull request merged**
