### PR TITLE
use verb practise in reference to OO training - fixes #539

### LINKED ISSUE #539: Grammar consistency
CC @franziskas 
https://codurance.com/services/training/ - Course title is 'Object Oriented Design **Practise**'
https://codurance.com/services/training/oo-design/ - Course title is 'Object Oriented Design **Practice**'

### PR DESCRIPTION
**Pull request by jukecraft**

### CODE REVIEW

**Comment by jukecraft** [comment]
@PaNaVTEC got this error message on CircleCi, can you help?
screen shot 2017-01-24 at 09 41 37

**Comment by PaNaVTEC** [comment]
I've just hit the "rebuild" button, sometimes we are not getting the PR number. I will investigate what happens, thanks for telling me :)

**Comment by jukecraft** [comment]
@PaNaVTEC this has taken a really long time to build, do you know why?
https://circleci.com/gh/codurance/site/41#config/containers/0

**Comment by PaNaVTEC** [comment]
@franziskas This is the normal time to build & deploy, it took 3:30 to deploy and 1:30 to build and the rest is setup & dependencies

**Pull request merged**
