### PR TITLE
Blog post about Jenkins pipeline

### PR DESCRIPTION
**Pull request by jaramir**

### CODE REVIEW

**Comment by jaramir** [comment]
I've created the PR because I want the preview. Don't merge yet :)

**Comment by Gryff** [comment]
The picture is a bit light for the white text title
image

**Comment by Gryff** [comment]
I like the idea, there is a lot of good stuff in the Acuris pipelines that could be promoted.

**Comment by jaramir** [comment]
image
trying a different background for the image

**Pull request merged**
