### PR TITLE
Change map marker to codurance office

### LINKED ISSUE #463: Map of codurance
The map is showing Market Research Society, it seems Google has updated the map to display Codurance at the right address, so need to change the map

### PR DESCRIPTION
**Pull request by ghost**
fixes #463

### CODE REVIEW

**Comment by CarlosMChica** [comment]
@halimakoundi I run the build with the current branch and looks fine but there are a lot of errors in the console, could you please have a look?

Thanks :)

**Comment by ghost** [comment]
I cannot see any console errors, could you send a screen shot please?

screen shot 2016-12-21 at 20 48 48

**Comment by neomatrix369** [comment]
@CarlosMChica I just checked by running it on my machine and there are no errors in the console, when I'm on the Company page, see below:

screen shot 2016-12-22 at 10 29 02

**Comment by CarlosMChica** [comment]
It was the ad blocker. However everything displays as expected so I wouldn't worry too much about the ad blocker showing some errors in the console

**Pull request merged**
