### PR TITLE
Added ability to search

### PR DESCRIPTION
**Pull request by MiyamotoAkira**
Basic ability to search on posts.

Probably we will want the search page to actually  be integrated inside publications, but is a starting point.

### CODE REVIEW

**Comment by mashooq** [comment]
Hi Jorge, I tried this in the preview branch and it doesn't seem to work.

**Comment by MiyamotoAkira** [comment]
Yeah, there is something happening on the deployed system. Works on my machine (ha ha). But for some reason it doesn't when deployed. Need to investigate further. I mentioned the issue on the slack channel

**Comment by cohen990** [comment]
I wonder if this is related to #777 ?

**Comment by MiyamotoAkira** [comment]
don't think so, the problem is related to the form action, which doesn't add the query parameter

**Comment by cohen990** [comment]
I'm gonna close this unless anybody objects

**Pull request closed without merging**
