### PR TITLE
Added some documentation for using backstopjs.

### PR DESCRIPTION
**Pull request by chriseyre2000**
Added some starter documentation for backstopjs.

### CODE REVIEW

**Comment by MiyamotoAkira** [comment]
I use the docker instance to run the app. Could this be run from docker?

**Comment by chriseyre2000** [comment]
It does have docker options:

https://github.com/garris/BackstopJS

**Comment by Mattsi-Jansky** [comment]
Do we need to add `npm install -g backstopjs` to `Dockerfile`?

**Comment by MiyamotoAkira** [comment]
Ideally yes. What we want is to avoid unnecessary installations on every single change we do in a post.

**Comment by chriseyre2000** [comment]
I have created an issue to create the docker image for this: #1131

This is more useful while refactoring css rather than on a build server.

This PR adds some documentation.

**Pull request merged**
