### PR TITLE
Better links in bullet point lists

### PR DESCRIPTION
**Pull request by jukecraft**
make links show up as defined in orange.css even when they are part of bullet points

### CODE REVIEW

**Comment by robertfirek** [comment]
I'm not sure if **_assets/css/style.css**_ is the part of Unify Bootstrap template. Modifying this file will not allow us to upgrade to the latest version of the template in the future.

**Comment by jukecraft** [comment]
It's a quick fix Mash came up with. We don't have a long term solution for these kinds of problems, if you have an idea, go ahead :)

**Comment by robertfirek** [comment]
We should have our own custom css file at the end of list of all css stylesheets. This stylesheet can override styles defined in the previous files.

**Comment by jukecraft** [comment]
We have a custom.css but we have not decided on how to deal with this. You can suggest something.

**Comment by robertfirek** [comment]
I think we can move all changes from style.css to custom.css. It should
change style on the site in the same way.

**Comment by jukecraft** [comment]
The problem is that I didn't add something, I removed something. How would we do that?

**Pull request merged**
