### PR TITLE
Adding Mango

### PR DESCRIPTION
**Pull request by charlyraffellini**
Adding mango in `/clients`

[Preview](https://codurance-site-pr.s3.amazonaws.com/site-adding-mango/clients/index.html)

### CODE REVIEW

**Comment by sjn88** [comment]
Mango.com doesn't appear to go anywhere, we should link to "http://shop.mango.com/iframe.faces?state=she_006_IN" (company page) or just "shop.mango.com" (home page)?

Also, what do people think about using apostrophes as thousand separators because it might make parsing easier for non-native speakers of English? Specifically aiming this as non-native speakers of English.

**Review by sjn88 — DISMISSED** [review]

**Comment by charlyraffellini** [comment]
mango.com redirects to shop.mango.com

We use apostrophes. However, I have never seen apostrophes as thousand separators. I use dot or comma.

**Comment by sjn88** [comment]
Mango.com wasn't redirecting appropriately when I made the comment. Also do we want to redirect to their sales site or their corporate site? I guess this is a question for @GiuliaMantuano

**Comment by GiuliaMantuano** [comment]
@charlyraffellini  @Seanseviltwin shop.mango.com will be fine. Thank you!

**Comment by charlyraffellini** [comment]
@GiuliaMantuano @Seanseviltwin I changed the link, let's see how the site looks after the build pass and we can merge.

**Comment by sjn88** [comment]
If it looks good to you feel free to merge it.

**Pull request merged**
