### PR TITLE
Redirect /fizzbuzz to Katalyst

### PR DESCRIPTION
**Pull request by jaramir**

### CODE REVIEW

**Comment by Mattsi-Jansky** [comment]
In preview it only works if you visit `index.htm`, visiting `http://codurance-site-pr.s3-website-eu-west-1.amazonaws.com/site-redirect-fizzbuzz/en/fizzbuzz` doesn't work. Presumably this is only because the S3 bucket is configured differently, and it'll work in production right?

**Comment by jaramir** [comment]
> it'll work in production right?

🤞

**Review by Mattsi-Jansky — APPROVED** [review]
Let's roll the 🎲

**Comment by jaramir** [comment]
> Let's roll the 🎲

nope, the /pubications redirect works on the preview so /fizzbuzz does not work for some reason

**Comment by Mattsi-Jansky** [comment]
Ah, good spot.

**Comment by jaramir** [comment]
wrong file extension 😄

**Review by Mattsi-Jansky — APPROVED** [review]
Good stuff, works now 👍

**Pull request merged**
