### PR TITLE
Update 2017-08-08-ddd-modeling.md

### PR DESCRIPTION
**Pull request by davidgrahamhall**
Updated 'Modeling' to 'Modelling'.

### CODE REVIEW

**Comment by PaNaVTEC** [comment]
Why do we need double L? 

https://en.wikipedia.org/wiki/Domain-specific_modeling

**Comment by davidgrahamhall** [comment]
Consistent with how he calls it: https://skillsmatter.com/courses/562-alberto-brandolini-s-ddd-modelling-workshop

**Comment by PaNaVTEC** [comment]
In the official book it is with one L, this is an extract of the first page: 

```
The software development community widely acknowledges that domain modeling is central to
software design. Through domain modeling, software developers are able to express rich
functionality and translate that functionality into software implementation that truly serves the
needs of its users. Despite its obvious importance, however, there are few practical resources that
show how to incorporate effective domain modeling into the software development process.
```

**Comment by davidgrahamhall** [comment]
Fair enough, lets stick with that! :-)

**Pull request closed without merging**
