### PR TITLE
Added myself to the team page on the company site

### PR DESCRIPTION
**Pull request by markg-codurance**

### CODE REVIEW

**Comment by keith-smale** [comment]
I can't see a branch on our repo for these changes. Can you create one?

**Comment by markg-codurance** [comment]
> I can't see a branch on our repo for these changes. Can you create one?

If you tell me what to do I can, but don't actually know much about github +PRs.

**Comment by markg-codurance** [comment]
> > I can't see a branch on our repo for these changes. Can you create one?
> 
> If you tell me what to do I can, but don't actually know much about github +PRs.

**Comment by markg-codurance** [comment]
I think it is because I forked, edited and then created a PR, looking at how others did it they made the changes on the actual repo. I'll do the same.

**Pull request closed without merging**
