### PR TITLE
New clients

### PR DESCRIPTION
**Pull request by anguspaterson**
Add new clients

### CODE REVIEW

**Comment by keith-smale** [comment]
Looks good, although I think we should have some copy about how we have helped each client, like we have for the other clients before merging.

**Comment by keith-smale** [comment]
Is there a reason why you've included the video hero banner commit from your other PR's in this branch? 

Personally, I would have expected to just see the changes to the clients section as per the PR and branch descriptions rather than changes to other sections from other PR's.
So the commits, branch and PR should relate to the change you are making.

**Comment by keith-smale** [comment]
We also have some clients listed on the 'Services' section. Should we adjust that section too?

**Comment by anguspaterson** [comment]
@keith-smale @davidgrahamhall - This branch got messy and appreciate there are some changes. Will amend and setup a new branch for these changes.

**Pull request closed without merging**
