### PR TITLE
setting image width to be no bigger than its container

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
fixes #495

**Comment by jukecraft** [comment]
Is this better?
Screenshot from my Chrome on Mac
screen shot 2017-01-10 at 15 59 41

**Comment by ghost** [comment]
It is not for those images, but for images inside the blog post

**Comment by jukecraft** [comment]
@halimakoundi I was comparing it to the screenshot in https://github.com/codurance/site/issues/452 - can you tell me which blog post to compare?

**Comment by ghost** [comment]
Sorry my bad I linked to the wrong issue, I meant to link it to #495

**Pull request merged**
